# suppress inspection "SpringBootApplicationProperties" for whole file
server.port=8100
server.servlet.context-path=/geoPoly
spring.data.mongodb.uri=mongodb://localhost:27017/test
springdoc.api-docs.path=/api-docs
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
google.autocomplete.api_key=AIzaSyCrBHL-a2XCCK7bdYDbhV3NKvV1m8-PK7E
locationiq.autocomplete.url=https://api.locationiq.com/v1/autocomplete.php
locationiq.autocomplete.api_key=3e8ce9797dfa56
